name: Build and Package Kafka FHIR Secure Sink

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Configure Maven settings for GitHub Packages
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        server-username: MAVEN_USERNAME
        server-password: MAVEN_TOKEN

    - name: Run tests
      run: mvn clean test

    - name: Build JAR with dependencies
      run: mvn clean compile assembly:single

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: kafka-fhir-secure-sink-jar
        path: target/kafka-fhir-secure-sink-*-jar-with-dependencies.jar
        retention-days: 90

    - name: Deploy to GitHub Packages (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: mvn deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ github.actor }}
        MAVEN_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: target/kafka-fhir-secure-sink-*-jar-with-dependencies.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}